### ISSUE TITLE
How it work ? 

### ISSUE THREAD

**Issue by AbdallahQoutbAli** [Bastian/Meeting-Parser#1]
How can run programming, i download NITE XML and AMI-metadata.xml

**Comment by Bastian** [comment]
Hi, 
what exactly is not working for you?
The README should describe everything you need to know to run the program.

Don't forget to update the path to the NXT toolkit in the `build.gradle` file: https://github.com/Bastian/Meeting-Parser/blob/master/build.gradle#L15

**Comment by AbdallahQoutbAli** [comment]
I do it, and try to run java main but it not work, give me error
 **"net.sourceforge.nite.meta.impl.NiteMetaData;"**
and try to using gradlew.bat it run but not any output, i change the path of NXT toolkit

**Comment by Bastian** [comment]
> "net.sourceforge.nite.meta.impl.NiteMetaData;"

This is no error, just the fully qualified class name. Are you getting a `ClassNotFoundException`?
